### ISSUE TITLE
Entity's in boats/minecarts are removed on lagg clearing

### ISSUE THREAD

**Issue by compieter-gh** [2mal3/No-Lag#11]
Any entity in a boat/minecart is removed/killed when the clear lagg commands are exxecuted.

**Comment by 2mal3** [comment]
Unfortunately, I cannot reproduce this with the information I currently have. It would be helpful if you could describe in a bit more detail what happens, what doesn't happen and which entities are affected. The datapack and Minecraft version would also be helpful.

**Comment by compieter-gh** [comment]
Datapack version: v3.1.3
MC version: 23w12a
Entity i had issues with was Villagers in a boat/minecarts.

I have looked myself at the datapack source and i did see nothing to prevent it from removing any entity(s) that are in boats /minecarts.

datapack/src/nola/modules/lag_clear.mc 
line 19 - 24 This would be where id expect to see such the exclusion for it.
line 32 - 37 I've tested what happens when an entity in an boat/minecart and it tp's it with it killing it in the void.
line 67 -118 Understandably no boat/minecart in exclusions but that would mean any entity in a boat/minecraft will be removed with it right or am i missing something?

Kinda tried understanding it myself i have no knowledge bout datapack creation though.

**Comment by 2mal3** [comment]
OK, I think I have found the problem now. In 1.19.4, when a boat is deleted, the entity riding the boat stays in place and is not killed, but apparently this was changed in 23w12a. There, the riding entity is now removed as well.

Thank you very much!

This bug will be only fixed in the update for Minecraft 1.20 update, as this version is currently in snapshots and I only support the full updates. If you still need the datapack urgently, you can build it from the 1.20 branch.

**Comment by compieter-gh** [comment]
Yeah i did that and this issue seems to be fixed. Thank you.
